#
# :Precis: Install an IBM MQ environment on the host
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

galaxy_info:
  author: Andrew Burrow
  description: >-
    Install an IBM MQ environment on the host

    This *action role* performs an environment install of IBM MQO.

    See `../../ibm_mq_define/defaults/main.yml` for details on the
    parameters.
  company: Syntegrity Solutions

dependencies:
  - role: ibm_mq_host_define
  - role: ibm_mq_environment_define
