#
# :Precis: Provision infrastructure on EIP hosts
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
# :Notes: This playbook is intended to target the `inf_*` groups
#

---

- name: Configure EIP hosts for IBM MQ and IBM ACE installations
  hosts: all
  gather_facts: false
  roles:
    - ibm_mq_host_config
    - ibm_ace_host_config
