#
# :Precis: Provision IBM MQ and IBM ACE environments on EIP hosts
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
# :Notes: This playbook is intended to target the `env_*` groups
#

---

- name: Install IBM MQ and IBM ACE environments on EIP hosts
  hosts: all
  gather_facts: false
  roles:
    - ibm_host_define
    - ibm_mq_host_define
    - ibm_ace_host_define
    - ibm_mq_environment_define
    - ibm_ace_environment_define
    - ibm_mq_environment_install
    - ibm_ace_environment_install
