#
# :Precis: Setup hosts for IBM MQ and ACE environments
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Setup hosts for IBM MQ and ACE
  hosts: all
  gather_facts: false
  roles:
    - ibm_host_define
    - ibm_mq_host_define
    - ibm_ace_environment_define
    - ibm_mq_host_config
    - ibm_ace_host_config
