#
# :Precis: Install an IBM MQ environment on the host
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Install rpm-build package
  become: true
  ansible.builtin.dnf:
    name: rpm-build
    state: present

# MQ Base Installation

- name: Create MQ base build directory
  become: true
  ansible.builtin.file:
    path: "{{ ibm_mq_environment_build_dir }}/base"
    state: directory
    mode: '0755'

- name: Extract MQ base installer
  become: true
  ansible.builtin.unarchive:
    src: "{{ ibm_mq_environment_source_dir }}/{{ ibm_mq_environment_package }}"
    dest: "{{ ibm_mq_environment_build_dir }}/base"
    remote_src: true
    creates: "{{ ibm_mq_environment_build_dir }}/base/MQServer"

- name: Create MQ package for environment
  become: true
  ansible.builtin.command:
    cmd: ./crtmqpkg {{ ibm_mq_environment }}
    chdir: "{{ ibm_mq_environment_build_dir }}/base/MQServer"
    creates: >-
      {{ ibm_mq_environment_build_dir }}/base/MQServer/mq_rpms/{{ ibm_mq_environment }}
  environment:
    TMPDIR: "{{ ibm_mq_environment_build_dir }}/base/MQServer"

- name: Install MQ base RPMs
  become: true
  ansible.builtin.shell:
    cmd: |
      rpm --prefix={{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm \
          -ivh MQSeriesRuntime*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm \
               MQSeriesClient*.rpm MQSeriesJava*.rpm MQSeriesMan*.rpm \
               MQSeriesSample*.rpm MQSeriesSDK*.rpm MQSeriesServer*.rpm \
               MQSeriesWeb*.rpm
    chdir: >-
      {{
        ibm_mq_environment_build_dir
      }}/base/MQServer/mq_rpms/{{ ibm_mq_environment }}/x86_64
    creates: >-
      {{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm/bin/mqlicense

- name: Accept MQ license
  become: true
  ansible.builtin.command:
    cmd: ./mqlicense -accept
    chdir: "{{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm/bin"
    creates: >-
      {{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm/.license_accepted

- name: Change environment folder permissions
  become: true
  ansible.builtin.file:
    path: "{{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}"
    mode: '0755'
    state: directory

# MQ Fixpack Installation

- name: Create MQ fixpack build directory
  become: true
  ansible.builtin.file:
    path: "{{ ibm_mq_environment_build_dir }}/fixpack"
    state: directory
    mode: '0755'

- name: Extract MQ fixpack
  become: true
  ansible.builtin.unarchive:
    src: "{{ ibm_mq_environment_source_dir }}/{{ ibm_mq_environment_fixpack_package }}"
    dest: "{{ ibm_mq_environment_build_dir }}/fixpack"
    remote_src: true
    creates: "{{ ibm_mq_environment_build_dir }}/fixpack/crtmqfp"

- name: Create MQ fixpack package
  become: true
  ansible.builtin.command:
    cmd: ./crtmqfp {{ ibm_mq_environment }}
    chdir: "{{ ibm_mq_environment_build_dir }}/fixpack"
    creates: "{{ ibm_mq_environment_build_dir }}/fixpack/mq_rpms/{{ ibm_mq_environment }}"
  environment:
    TMPDIR: "{{ ibm_mq_environment_build_dir }}/fixpack"

- name: Install MQ fixpack RPMs
  become: true
  ansible.builtin.shell:
    cmd: |
      rpm --prefix={{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm \
          -Uvh MQSeriesRuntime*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm \
               MQSeriesClient*.rpm MQSeriesJava*.rpm MQSeriesMan*.rpm \
               MQSeriesSample*.rpm MQSeriesSDK*.rpm MQSeriesServer*.rpm \
               MQSeriesWeb*.rpm
    chdir: >-
      {{ ibm_mq_environment_build_dir }}/fixpack/mq_rpms/{{ ibm_mq_environment }}/x86_64
  register: fixpack_install
  changed_when: "'Upgrading' in fixpack_install.stdout or 'Installing' in fixpack_install.stdout"
  failed_when:
    - fixpack_install.rc != 0
    - "'is already installed' not in fixpack_install.stderr"

# Queue Manager Creation

- name: Create directory for queue manager INI overrides
  become: true
  ansible.builtin.file:
    path: "{{ ibm_mq_host_base_dir }}/{{ ibm_mq_environment }}/mqm/config"
    state: directory
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: "ug=rwx,o=rx"

- name: Copy queue manager INI overrides
  become: true
  ansible.builtin.copy:
    src: qm_overrides.ini
    dest: >-
      {{ ibm_mq_host_base_dir }}/{{
        ibm_mq_environment
      }}/mqm/config/{{ item.queue_manager }}-autoconfig.ini
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: 'u=rw,g=r'
  loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

- name: Create queue managers
  become: true
  become_user: "{{ ibm_mq_host_user }}"
  ansible.builtin.command:
    cmd: >-
      crtmqm
      -c "{{ item.qmtype }}"
      -lc
      -lf 8192
      -lp 10
      -ls 4
      -ii {{ ibm_mq_host_base_dir }}/{{
        ibm_mq_environment
      }}/mqm/config/{{ item.queue_manager }}-autoconfig.ini
      -u SYSTEM.DEAD.LETTER.QUEUE
      {{ item.queue_manager }}
  environment:
    PATH: >-
      {{ ibm_mq_host_base_dir }}/{{
        ibm_mq_environment
      }}/mqm/bin:/usr/local/bin:/usr/bin:/bin
  register: create_qm
  changed_when: "'created' in create_qm.stdout"
  failed_when:
    - create_qm.rc != 0
    - "'already exists' not in create_qm.stderr"
  loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

- name: Install queue manager certificate stores
  become: true
  ansible.builtin.copy:
    src: >-
      {{ ibm_mq_environment_source_dir }}/ssl_kdb/{{
        item.0.queue_manager
      }}/{{ item.0.queue_manager }}.{{ item.1 }}
    dest: >-
      /var/mqm/qmgrs/{{ item.0.queue_manager }}/ssl/keys.{{ item.1 }}
    remote_src: true
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: "u=rw,g=rw"
  loop: >-
    {{
      ibm_mq_environment_itsshelper_qmgr_props
      | product(['kdb', 'rdb', 'sth', 'crl'])
      | list
    }}

- name: Generate MQSC files for queue manager configuration
  become: true
  become_user: "{{ ibm_mq_host_user }}"
  ansible.builtin.command:
    cmd: >-
      /opt/scripts/translate.bash
      {{ ibm_mq_environment }}
      {{ item.propfile }}
      /tmp/{{ ibm_mq_environment }}_{{ item.queue_manager }}.mqsc
  changed_when: false
  loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

- name: Install MQSC files for queue manager configuration
  become: true
  ansible.builtin.copy:
    src: /tmp/{{ ibm_mq_environment }}_{{ item.queue_manager }}.mqsc
    dest: >-
      /opt/properties/{{ ibm_mq_environment }}_{{ item.qmtype }}.mqsc
    remote_src: true
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: 'u=rw,g=r'
  register: install_mqsc
  loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

- name: Run MQSC files for queue manager configuration
  ansible.builtin.include_tasks:
    file: run_qmgr_mqsc.yml
  when: result.changed
  loop: "{{ install_mqsc.results }}"
  loop_control:
    loop_var: result

# - name: Install systemd unit template for queue managers
#   become: true
#   ansible.builtin.file:
#     src: >-
#       {{ ibm_mq_host_base_dir }}/{{
#         ibm_mq_environment
#       }}/mqm/lib/systemd/system/mq@.service
#     dest: /etc/systemd/system/mq_{{ ibm_mq_environment }}@.service
#     state: link

# - name: Enable systemd services for queue managers
#   become: true
#   ansible.builtin.systemd:
#     name: "mq_{{ ibm_mq_environment }}@{{ item.queue_manager }}.service"
#     enabled: true
#     daemon_reload: true
#   loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

# - name: Start queue managers via systemd
#   become: true
#   ansible.builtin.systemd:
#     name: "mq_{{ ibm_mq_environment }}@{{ item.queue_manager }}.service"
#     state: started
#   loop: "{{ ibm_mq_environment_itsshelper_qmgr_props }}"

# MQ App Creation

- name: Generate MQSC files for MQ app configuration
  become: true
  become_user: "{{ ibm_mq_host_user }}"
  ansible.builtin.command:
    cmd: >-
      /opt/scripts/translate.bash
      {{ ibm_mq_environment }}
      {{ item.propfile }}
      /tmp/{{ ibm_mq_environment }}_{{ item.queue_manager }}_{{ item.propfile }}.mqsc
  changed_when: false
  loop: "{{ ibm_mq_environment_itsshelper_mqapp_props }}"

- name: Install MQSC files for MQ app configuration
  become: true
  ansible.builtin.copy:
    src: >-
      /tmp/{{ ibm_mq_environment }}_{{ item.queue_manager }}_{{ item.propfile }}.mqsc
    dest: >-
      /opt/properties/{{ ibm_mq_environment }}_{{ item.qmtype }}_{{ item.propfile }}.mqsc
    remote_src: true
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: 'u=rw,g=r'
  register: install_mqsc
  loop: "{{ ibm_mq_environment_itsshelper_mqapp_props }}"

- name: Run MQSC files for MQ app configuration
  ansible.builtin.include_tasks:
    file: run_mqapp_mqsc.yml
  when: result.changed
  loop: "{{ install_mqsc.results }}"
  loop_control:
    loop_var: result

- name: Run MQSC files for MQ app configuration
  become: true
  become_user: "{{ ibm_mq_host_user }}"
  ansible.builtin.command:
    cmd: >-
      runmqsc
      -f /opt/properties/{{ ibm_mq_environment }}_{{ item.qmtype }}_{{ item.propfile }}.mqsc
      {{ result.item.queue_manager }}
  environment:
    PATH: >-
      {{ ibm_mq_host_base_dir }}/{{
        ibm_mq_environment
      }}/mqm/bin:/usr/local/bin:/usr/bin:/bin
  register: configure_qm
  changed_when: true
  when: result.changed
  loop: "{{ install_mqsc.results }}"
  loop_control:
    loop_var: result

# User Configuration

- name: Configure mqm user aliases
  become: true
  ansible.builtin.blockinfile:
    path: "/home/{{ ibm_mq_host_user }}/.bashrc"
    block: >-
      alias {{
        ibm_mq_environment
      }}=". {{
        ibm_mq_host_base_dir
      }}/{{ ibm_mq_environment }}/mqm/bin/setmqenv -s"
    marker: "# {mark} ANSIBLE MANAGED MQ ALIASES FOR {{ ibm_mq_environment }}"
    create: true
    owner: "{{ ibm_mq_host_user }}"
    group: "{{ ibm_mq_host_group }}"
    mode: '0644'
