#
# :Precis: Enumerate all hosts for group structure with virtual hosts
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

all:
  children:
    common_np1:
      children:
        inf_np1:
          hosts:
            sduace0101-np1:
              ansible_connection: sduace0101.melb.ad
            sduace0201-np1:
              ansible_connection: sduace0201.melb.ad
        env_ci1:
          hosts:
            sduace0101-ci1:
              ansible_connection: sduace0101.melb.ad
            sduace0201-ci1:
              ansible_connection: sduace0201.melb.ad
        env_dv1:
          hosts:
            sduace0101-dv1:
              ansible_connection: sduace0101.melb.ad
            sduace0201-dv1:
              ansible_connection: sduace0201.melb.ad
        env_ps1:
          hosts:
            sduace0101-ps1:
              ansible_connection: sduace0101.melb.ad
            sduace0201-ps1:
              ansible_connection: sduace0201.melb.ad
    common_np2:
      children:
        inf_np2:
          hosts:
            stuace0101-np2:
              ansible_connection: stuace0101.melb.ad
            stuace0201-np2:
              ansible_connection: stuace0201.melb.ad
        env_ts1:
          hosts:
            stuace0101-ts1:
              ansible_connection: stuace0101.melb.ad
            stuace0201-ts1:
              ansible_connection: stuace0201.melb.ad
        env_ts2:
          hosts:
            stuace0101-ts2:
              ansible_connection: stuace0101.melb.ad
            stuace0201-ts2:
              ansible_connection: stuace0201.melb.ad
        env_ts3:
          hosts:
            stuace0101-ts3:
              ansible_connection: stuace0101.melb.ad
            stuace0201-ts3:
              ansible_connection: stuace0201.melb.ad
    common_svt:
      children:
        inf_svt:
          hosts:
            svuace0101-svt:
              ansible_connection: svuace0101.melb.ad
            svuace0201-svt:
              ansible_connection: svuace0201.melb.ad
        env_sv1:
          hosts:
            svuace0101-sv1:
              ansible_connection: svuace0101.melb.ad
            svuace0201-sv1:
              ansible_connection: svuace0201.melb.ad
    common_preprod:
      children:
        inf_preprod:
          hosts:
            sauace0101-preprod:
              ansible_connection: svuace0101.melb.ad
            sauace0201-preprod:
              ansible_connection: svuace0201.melb.ad
        env_pat:
          hosts:
            sauace0101-pat:
              ansible_connection: svuace0101.melb.ad
            sauace0201-pat:
              ansible_connection: svuace0201.melb.ad
