#
# :Precis: Enumerate all hosts according to the group structure
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

all:
  children:
    cluster_np1:
      children:
        env_np1_ci1:
          hosts:
            sduace0101
            sduace0201
        env_np1_dv1:
          hosts:
            sduace0101
            sduace0201
        env_np1_ps1:
          hosts:
            sduace0101
            sduace0201
    cluster_np2:
      children:
        env_np2_ts1:
          hosts:
            stuace0101
            stuace0201
        env_np2_ts2:
          hosts:
            stuace0101
            stuace0201
        env_np2_ts3:
          hosts:
            stuace0101
            stuace0201
    cluster_svt:
      children:
        env_svt_sv1:
          hosts:
            svuace0101
            svuace0201
    cluster_preprod:
      children:
        env_preprod_pat:
          hosts:
            sauace0101
            sauace0201
    cluster_prod:
      children:
        env_prod_prod:
          hosts:
            spuace0101
            spuace0201
