#
# :Precis: Enumerate all hosts for group structure with virtual hosts
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

all:
  children:
    common_azure:
      children:
        inf_azure:
          hosts:
            localhost-azure:
              ansible_connection: local
        env_poc:
          hosts:
            localhost-poc:
              ansible_connection: local
