#
# :Precis: Enumerate all hosts according to the group structure
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

all:
  children:
    cluster_poc:
      children:
        env_poc_sx1:
          hosts:
            localhost:
              ansible_connection: local
