#
# :Precis: Config the host for IBM App Connect Enterprise installs
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Create aceadmin user
  become: true
  ansible.builtin.user:
    name: "{{ ibm_ace_host_user }}"
    uid: "{{ ibm_ace_host_uid | default(omit) }}"
    group: "{{ ibm_ace_host_group }}"
    groups: "{{ ibm_ace_host_additional_groups }}"
    password: "!"
    state: present

- name: Create ACE data directory
  become: true
  ansible.builtin.file:
    path: /var/mqsi
    state: directory
    mode: '0775'
    group: "{{ ibm_ace_host_group }}"

- name: Add root to mqbrkrs group
  become: true
  ansible.builtin.user:
    name: root
    groups: "{{ ibm_ace_host_group }}"
    append: true

- name: Add administrative users to mqbrkrs group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ ibm_ace_host_group }}"
    append: true
  loop: "{{ ibm_ace_host_users }}"
  when: ibm_ace_host_users | length > 0

- name: Install packages required for network filesystems
  become: true
  ansible.builtin.dnf:
    name:
      - cifs-utils
      - nfs-utils
    state: present

- name: Create CIFS credential files for mount points
  become: true
  ansible.builtin.copy:
    content: "{{ item.credential_secret }}"
    dest: "{{ item.credential_file }}"
    owner: root
    group: root
    mode: '0600'
  loop: >-
    {{
      dict(
        ibm_ace_host_mounts
        | selectattr('type', 'equalto', 'cifs')
        | map(attribute='credential_file')
        | zip(ibm_ace_host_mounts | selectattr('type', 'equalto', 'cifs'))
      ).values() | list
    }}
  no_log: true

- name: Mount network filesystems for ACE
  become: true
  ansible.posix.mount:
    src: "{{ item.server }}"
    path: "{{ item.mount_point }}"
    fstype: "{{ item.type }}"
    opts: >-
      {{
        item.options
        + ((',credentials=' + item.credential_file
        + ',uid=' + item.uid
        + ',gid=' + item.gid) if item.type == 'cifs' else '')
      }}
    state: mounted
    dump: 0
    passno: 0
  loop: "{{ ibm_ace_host_mounts }}"

- name: Create ACE profile script
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/ace.sh
    mode: '0644'
    content: |
      ace_init()
      {
          env=$1
          if [ -n "${env}" ]; then
              ACE_BIN={{ ibm_ace_host_base_dir }}/${env}/ace/server/bin
              source ${ACE_BIN}/mqsiprofile
              export ODBCSYSINI="/var/mqsi/${env}/config"
              export ODBCINI=${ODBCSYSINI}/odbc.ini
              echo "ODBCINI: $ODBCINI"
              echo "ODBCSYSINI: $ODBCSYSINI"
          else
              echo "USAGE: ace_init <environment name>"
          fi
      }

- name: Configure aceadmin bash profile
  become: true
  ansible.builtin.blockinfile:
    path: "/home/{{ ibm_ace_host_user }}/.bash_profile"
    block: |
      echo "INFO: to initialise ACE, use \"ace_init <env>\", e.g. \"ace_init sx1\""
      echo "INFO: to switch environments:"
      echo "  1) log out"
      echo "  2) log back in"
      echo "  3) re-run ace_init with new environment name"
    marker: "# {mark} ANSIBLE MANAGED ACE INIT"
    create: true
    owner: "{{ ibm_ace_host_user }}"
    group: "{{ ibm_ace_host_group }}"
    mode: '0644'
