# The file supports comments indicated with # in column 1
# The file contains a set of triplets for the Object, Name and Value of Integration Server configuration
# The file name is structure to work with a script finding it. 
# The first name element is 'iib'
# The second name element is 'is'
# The third name element is the type (one of 'tac' 'common' or 'vwa')
# Each line is read, and applied in :
#   mqsichangeproperties IntNode -e IS-{env}-{type} -o {Object} -n {Name} -v {Value}
# After the changes in this file are applied, the Integration Server needs to be restarted
# Empty lines in the file are also ignored
