# properties to control automatic signing of MQ certs
#
# Use associative arrays indexed by environment letter
# to determine whether automatic signing is performed, and
# how it is done (which CA, what credentials)

declare -A MQAUTOSIGNLIST
declare -A MQCASERVERLIST
declare -A MQCACREDFILELIST
declare -A MQCAUSERNAMELIST

# Specifies whether autosign is performed in each environment
MQAUTOSIGNLIST=( \
	[X]=yes \
	[D]=yes \
	[T]=yes \
	[V]=yes \
	[A]=no \
	[P]=no \
	)
# Specifies the server that contains the CA for each environment
MQCASERVERLIST=( \
	[X]=sxuwmq0201 \
	[D]=sxuwmq0201 \
	[T]=sxuwmq0201 \
	[V]=sxuwmq0201 \
	[A]=winvmca1 \
	[P]=winvmca1 \
	)
# Specifies the file containing the ssh RSA key to access the CA userid
# on the provided CA server. This file is held in the properties directory.
MQCACREDFILELIST=( \
	[X]=caIdentity_rsa \
	[D]=caIdentity_rsa \
	[T]=caIdentity_rsa \
	[V]=caIdentity_rsa \
	[A]=caIdentity_rsa \
	[P]=caIdentity_rsa \
	)
# Specifies the userid which hosts the CA used to sign the certificates
# when autosigning is used.
MQCAUSERNAMELIST=( \
	[X]=ca \
	[D]=ca \
	[T]=ca \
	[V]=ca \
	[A]=ca \
	[P]=ca \
	)