#
# :Precis: Config the host for IBM App Connect Enterprise installs
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

galaxy_info:
  author: Andrew Burrow
  description: >-
    Config the host for IBM App Connect Enterprise installs

    This *action role* sets up the host for environment installs of IBM App
    Connect Enterprise.

    See `../../ibm_ace_define/defaults/main.yml` for details on the
    parameters.
  company: Syntegrity Solutions

dependencies:
  - role: ibm_ace_host_define
