#
# :Precis: Install an IBM ACE environment on the host
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

# ACE Installation

- name: Create ACE installation directory
  become: true
  ansible.builtin.file:
    path: "{{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}"
    state: directory
    mode: '0755'

- name: Extract ACE installer
  become: true
  ansible.builtin.unarchive:
    src: >-
      {{ ibm_ace_environment_source_dir }}/{{ ibm_ace_environment_package }}
    dest: "{{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}"
    remote_src: true
    creates: >-
      {{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}/ace-{{
        ibm_ace_environment_version
      }}

- name: Accept ACE license silently
  become: true
  ansible.builtin.command:
    cmd: ./ace make registry global accept license silently
    chdir: >-
      {{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}/ace-{{
        ibm_ace_environment_version
      }}

- name: Create symbolic link for ACE
  become: true
  ansible.builtin.file:
    src: >-
      {{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}/ace-{{
        ibm_ace_environment_version
      }}
    dest: >-
      {{ ibm_ace_environment_base_dir }}/{{ ibm_ace_environment }}/ace
    state: link

# Integration Node Creation

- name: Create integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsicreatebroker {{ item.name }}
      -q {{ item.queue_manager }}
      -w {{ ibm_ace_environment_work_path }}
  register: create_node
  changed_when: "'BIP1284I' in create_node.stdout"
  failed_when:
    - create_node.rc != 0
    - "'BIP1275E' not in create_node.stderr"
    - "'BIP8087E' not in create_node.stdout"
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Create and store the MQ vault key
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsivault {{ item.name }} --create
      --vault-key {{ ibm_ace_environment_vault_secret }} ;
      mqsivault {{ item.name }} --vaultrc-store-key
      --vault-key {{ ibm_ace_environment_vault_secret }}
  loop: "{{ ibm_ace_environment_integration_nodes }}"
  no_log: false

- name: Start integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsistart {{ item.name }}
  register: start_node
  changed_when: "'BIP1284I' in start_node.stdout"
  failed_when:
    - start_node.rc != 0
    - "'BIP1286E' not in start_node.stderr"
    - "'BIP8018E' not in start_node.stdout"
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Set port of web admin for integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.name }}
      -b webadmin
      -o HTTPConnector
      -n port
      -v {{ item.webadmin_port }}
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Set IP address of web admin for integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.name }}
      -b webadmin
      -o HTTPConnector
      -n host
      -v {{ ibm_ace_environment_webadmin_ip }}
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Set authentication mode of web admin for integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeauthmode {{ item.name }}
      -b {{ ibm_ace_environment_webadmin_mode }}
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Create login on web admin of integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsiwebuseradmin {{ item.name }}
      -c -u {{ ibm_ace_environment_webadmin_user }}
      -a {{ item.webadmin_secret }}
      -r {{ ibm_ace_environment_webadmin_role }}
  register: create_login
  changed_when: create_login.rc == 0
  failed_when:
    - create_login.rc != 0
    - "'BIP2832E' not in create_login.stdout"
  loop: "{{ ibm_ace_environment_integration_nodes }}"
  no_log: true

# SSL Certificate Configuration

- name: Create SSL directory
  become: true
  ansible.builtin.file:
    path: "{{ ibm_ace_environment_work_path }}/ssl"
    state: directory
    owner: "{{ ibm_ace_host_user }}"
    group: "{{ ibm_ace_host_group }}"
    mode: '0770'

- name: Copy certificate p12 file
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        ibm_ace_environment_source_dir
      }}/{{ ibm_ace_environment_cert_p12 }}
    dest: >-
      {{
        ibm_ace_environment_work_path
      }}/ssl/{{ ibm_ace_environment_cert_p12 }}
    remote_src: true
    owner: "{{ ibm_ace_host_user }}"
    group: "{{ ibm_ace_host_group }}"
    mode: '0770'

- name: Configure SSL certificate for integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.name }}
      -b webadmin
      -o HTTPConnector
      -n sslCertificate
      -v '{{ ibm_ace_environment_work_path }}/ssl/{{ ibm_ace_environment_cert_p12 }}'
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Configure SSL password for integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.name }}
      -b webadmin
      -o HTTPConnector
      -n sslPassword
      -v {{ ibm_ace_environment_cert_secret }}
  loop: "{{ ibm_ace_environment_integration_nodes }}"

- name: Create integration servers
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsicreateexecutiongroup {{ item.0.name }} -e {{ item.1.name }}
  register: create_server
  changed_when: create_server.rc == 0
  failed_when:
    - create_server.rc != 0
    - "'BIP1151E' not in create_server.stdout"
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('integration_servers', skip_missing=True)
    }}

- name: Set port of integration servers
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.0.name }}
      -e {{ item.1.name }}
      -o HTTPConnector
      -n ListenerPort
      -v {{ item.1.port }}
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('integration_servers', skip_missing=True)
    }}

- name: Set JRE version of integration servers
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      ibmint specify jre --version {{ item.1.jre_version }}
      --integration-node {{ item.0.name }}
      --integration-server {{ item.1.name }}
      --verbose
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('integration_servers', skip_missing=True)
    }}

- name: Install JVM configuration files for environment
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/ace/{{ ibm_ace_environment }}/config/{{ item }}"
    owner: aceadmin
    group: mqbrkrs
    mode: "u=rw,go=r"
  loop: "{{ ibm_ace_environment_jvm_configs }}"

- name: Set JVM system properties of integration servers
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsichangeproperties {{ item.0.name }}
      -e {{ item.1.name }}
      -o ComIbmJVMManager
      -n jvmSystemProperty
      -v "-Dlog4j.configurationFile=/var/ace/{{ ibm_ace_environment }}/config/eip-vwa-log4j2.xml -Deip.config=/var/ace/{{ ibm_ace_environment }}/config/eip-config.xml"
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('integration_servers', skip_missing=True)
    }}

- name: Install ACE server configuration files
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.template:
    src: server.conf.yaml.j2
    dest: >-
      {{ ibm_ace_environment_work_path }}/components/{{
        node.name
      }}/servers/{{ server.name }}/server.conf.yaml
  vars:
    node: "{{ item.0 }}"
    server: "{{ item.1 }}"
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('integration_servers', skip_missing=True)
    }}

- name: Chown ACE software id tag directory to set the operation mode
  become: true
  ansible.builtin.file:
    path: /opt/ibm/{{ ibm_ace_environment }}/ace-13.0.6.2/swidtag
    owner: aceadmin
    group: mqbrkrs
    recurse: yes

- name: Set ACE operation mode
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      ibmint set mode {{ ibm_ace_environment_operation_mode }} --silently

- name: Create credentials in vault of each integration node
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsicredentials {{ item.0.name }}
      --all-integration-servers --create
      --credential-name {{ item.1.name }}
      --credential-type {{ item.1.type }}
      --username {{ item.1.username }}
      --password {{ item.1.secret }}
  register: create_credential
  changed_when: create_credential.rc == 0
  failed_when:
    - create_credential.rc != 0
    - "'BIP9505E' not in create_credential.stdout"
  loop: >-
    {{
      ibm_ace_environment_integration_nodes
      | subelements('credentials', skip_missing=True)
    }}

- name: Install ODBC configuration files for environment
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ibm_ace_environment_work_path }}/config/{{ item }}"
    owner: aceadmin
    group: mqbrkrs
    mode: "u=rw,go=r"
  loop: "{{ ibm_ace_environment_odbc_configs }}"

# XXX This should be a handler
- name: Restart integration nodes
  become: true
  become_user: "{{ ibm_ace_host_user }}"
  loop: "{{ ibm_ace_environment_integration_nodes }}"
  ansible.builtin.shell:
    cmd: >-
      source {{
        ibm_ace_environment_base_dir
      }}/{{ ibm_ace_environment }}/ace/server/bin/mqsiprofile ;
      mqsistop {{ item.name }} ;
      mqsistart {{ item.name }}
