# Managed by Ansible - ibm_mq_host_config
AuthorizationService:
   SecurityPolicy=user

Channels:
   MaxChannels=1000
   MaxActiveChannels=1000
   AdoptNewMCA=ALL
   AdoptNewMCATimeout=60
   AdoptNewMCACheck=QM,NAME

Security:
   ClusterQueueAccessControl=RQMName

SSL:
   CDPCheckExtensions=NO
   OCSPCheckExtensions=NO
   OCSPAuthentication=OPTIONAL
