BOOTSTRAP_ADDRESS=10000
CELL_DISCOVERY_ADDRESS=10001
CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS=10002
CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS=10003
DataPowerMgr_inbound_secure=10004
DCS_UNICAST_ADDRESS=10005
IPC_CONNECTOR_ADDRESS=10006
ORB_LISTENER_ADDRESS=10007
OVERLAY_UDP_LISTENER_ADDRESS=10008
OVERLAY_TCP_LISTENER_ADDRESS=10009
SAS_SSL_SERVERAUTH_LISTENER_ADDRESS=10010
SOAP_CONNECTOR_ADDRESS=10011
STATUS_LISTENER_ADDRESS=10012
WC_adminhost=10013
WC_adminhost_secure=10014
XDAGENT_PORT=10015