BOOTSTRAP_ADDRESS=10020
CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS=10021
CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS=10022
DCS_UNICAST_ADDRESS=10023
IPC_CONNECTOR_ADDRESS=10024
NODE_DISCOVERY_ADDRESS=10025
NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS=10026
NODE_MULTICAST_DISCOVERY_ADDRESS=10027
ORB_LISTENER_ADDRESS=10028
OVERLAY_UDP_LISTENER_ADDRESS=10029
OVERLAY_TCP_LISTENER_ADDRESS=10030
SAS_SSL_SERVERAUTH_LISTENER_ADDRESS=10031
SOAP_CONNECTOR_ADDRESS=10032
XDAGENT_PORT=10033