# This property file contains the information about
# which CA certificates should be loaded into the
# key/trust stores in each environment.
declare -a CA_Certs
declare -a CA_Labels
if [ "$E" == "X" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/vwa_dev_enterprise_ca.cer" \
    "${CONFIGDIR}/vwadevopsca.cer" \
    "${CONFIGDIR}/vwadevopscasha2.cer" \
    )
CA_Labels=( \
    "VWA Dev Enterprise Root CA" \
    "VWA DevOps CA" \
    "VWA DevOps SHA2 CA" \
    )
fi
if [ "$E" == "D" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/vwa_dev_enterprise_ca.cer" \
    "${CONFIGDIR}/vwadevopsca.cer" \
    "${CONFIGDIR}/vwadevopscasha2.cer" \
    "${CONFIGDIR}/vwa_enterprise_ca.cer" \
    "${CONFIGDIR}/tac_root_ca.cer" \
    "${CONFIGDIR}/winvmca1.cer" \
    "${CONFIGDIR}/winvmca2.cer" \
    "${CONFIGDIR}/vwatempca.cer" \
    "${CONFIGDIR}/tac_root_ca_sha2.cer" \
    "${CONFIGDIR}/winvmca1_sha2.cer" \
    "${CONFIGDIR}/winvmca2_sha2.cer" \
    )
CA_Labels=( \
    "VWA Dev Enterprise Root CA" \
    "VWA DevOps CA" \
    "VWA DevOps SHA2 CA" \
    "VWA Enterprise Root CA" \
    "TAC Root CA" \
    "Worksafe primary signing CA WINVMCA1" \
    "Worksafe secondary signing CA WINVMCA2" \
    "VWA Temp CA" \
    "TAC Root SHA2 CA" \
    "Worksafe primary signing SHA2 CA WINVMCA1" \
    "Worksafe secondary signing SHA2 CA WINVMCA2" \
    )
fi
if [ "$E" == "T" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/vwa_dev_enterprise_ca.cer" \
    "${CONFIGDIR}/vwadevopsca.cer" \
    "${CONFIGDIR}/vwadevopscasha2.cer" \
    "${CONFIGDIR}/vwa_enterprise_ca.cer" \
    "${CONFIGDIR}/tac_root_ca.cer" \
    "${CONFIGDIR}/winvmca1.cer" \
    "${CONFIGDIR}/winvmca2.cer" \
    "${CONFIGDIR}/vwatempca.cer" \
    "${CONFIGDIR}/tac_root_ca_sha2.cer" \
    "${CONFIGDIR}/winvmca1_sha2.cer" \
    "${CONFIGDIR}/winvmca2_sha2.cer" \
    )
CA_Labels=( \
    "VWA Dev Enterprise Root CA" \
    "VWA DevOps CA" \
    "VWA DevOps SHA2 CA" \
    "VWA Enterprise Root CA" \
    "TAC Root CA" \
    "Worksafe primary signing CA WINVMCA1" \
    "Worksafe secondary signing CA WINVMCA2" \
    "VWA Temp CA" \
    "TAC Root SHA2 CA" \
    "Worksafe primary signing SHA2 CA WINVMCA1" \
    "Worksafe secondary signing SHA2 CA WINVMCA2" \
    )
fi
if [ "$E" == "V" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/vwa_dev_enterprise_ca.cer" \
    "${CONFIGDIR}/vwadevopsca.cer" \
    "${CONFIGDIR}/vwadevopscasha2.cer" \
    "${CONFIGDIR}/vwa_enterprise_ca.cer" \
    "${CONFIGDIR}/tac_root_ca.cer" \
    "${CONFIGDIR}/winvmca1.cer" \
    "${CONFIGDIR}/winvmca2.cer" \
    "${CONFIGDIR}/vwatempca.cer" \
    "${CONFIGDIR}/tac_root_ca_sha2.cer" \
    "${CONFIGDIR}/winvmca1_sha2.cer" \
    "${CONFIGDIR}/winvmca2_sha2.cer" \
    )
CA_Labels=( \
    "VWA Dev Enterprise Root CA" \
    "VWA DevOps CA" \
    "VWA DevOps SHA2 CA" \
    "VWA Enterprise Root CA" \
    "TAC Root CA" \
    "Worksafe primary signing CA WINVMCA1" \
    "Worksafe secondary signing CA WINVMCA2" \
    "VWA Temp CA" \
    "TAC Root SHA2 CA" \
    "Worksafe primary signing SHA2 CA WINVMCA1" \
    "Worksafe secondary signing SHA2 CA WINVMCA2" \
    )
fi
if [ "$E" == "A" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/winvmca1_2023.cer" \
    "${CONFIGDIR}/vwa_enterprise_root_2023.cer" \
    "${CONFIGDIR}/tac_root_ca_2023.cer" \
    )
CA_Labels=( \
    "WINVMCA1" \
    "VWA Enterprise Root CA_2022" \
    "TAC_Root_CA" \
    )
fi
if [ "$E" == "P" ] ; then
CA_Certs=( \
    "${CONFIGDIR}/vwa_enterprise_ca.cer" \
    "${CONFIGDIR}/tac_root_ca.cer" \
    "${CONFIGDIR}/winvmca1.cer" \
    "${CONFIGDIR}/winvmca2.cer" \
    "${CONFIGDIR}/tac_root_ca_sha2.cer" \
    "${CONFIGDIR}/winvmca1_sha2.cer" \
    "${CONFIGDIR}/winvmca2_sha2.cer" \
    )
CA_Labels=( \
    "VWA Enterprise Root CA" \
    "TAC Root CA" \
    "Worksafe primary signing CA WINVMCA1" \
    "Worksafe secondary signing CA WINVMCA2" \
    "TAC Root SHA2 CA" \
    "Worksafe primary signing SHA2 CA WINVMCA1" \
    "Worksafe secondary signing SHA2 CA WINVMCA2" \
    )
fi
