# Declares a mapping from the 1 character host env letter
# to a 3 character environment name.
#
declare -A MQEnvMap
#
MQEnvMap=( \
	[X]="POC" \
	[D]="DEV" \
	[T]="TST" \
    [V]="TST" \
    [A]="PRD" \
	[P]="PRD" \
	)
#

