#
# /opt/properties/mqenvironments.properties
#
# -   Map the 1 character env letter that was formerly in the host name to a
#     3 character environment name to determine connectivity of each queue
#     manager in the cluster to the full repository that it should connect to.
#
# -   Map the 3 character env name used in the new host naming convention to the
#     original 1 character environment name, so that the previous naming
#     convention can also be determined
#
# -   Derived from properties file in `itsshelper` repository
#
declare -A MQEnvMap
declare -A MQEnvMap
#
MQEnvMap=( \
    [X]="POC" \
    [D]="DEV" \
    [T]="TST" \
    [V]="TST" \
    [A]="PRD" \
    [P]="PRD" \
    )
#
MQRevEnvMap=( \
    [SX1]="X" \
    [DV1]="D" \
    [CS1]="D" \
    [PS1]="D" \
    [TS1]="T" \
    [TS2]="T" \
    [TS3]="T" \
    [SV1]="V" \
    [PA1]="A" \
    [PR1]="P" \
    )
#
