#
# /opt/properties/mqgateway.properties
#
# -   Map the connectivity of each gateway queue manager in a cluster to
#     the matching AWS queue manager name
#
# -   All queue managers defined in all clusters (i.e. all environments)
#     are listed.
#
# -   Derived from properties file in `itsshelper` repository
#

# MQGWYLIST is an associative array using the actual queue manager
# name as the index. The value of the element is the name of the
# AWS queue manager to which the gateway connects.
declare -A MQGWYLIST
MQGWYLIST=( \
    [CI1DG0201]=CI1DMA101 \
    [CI1DG0101]=CI1DMA101 \
    [DV1DG0201]=DV1DMA201 \
    [DV1DG0101]=DV1DMA201 \
    [PS1DG0201]=PS1TMA101 \
    [PS1DG0101]=PS1TMA101 \
    [TS1TG0201]=TS4TMA201 \
    [TS1TG0101]=TS4TMA201 \
    [TS2TG0201]=TS3TMA301 \
    [TS2TG0101]=TS3TMA301 \
    [TS3TG0201]=TS3TMA301 \
    [TS3TG0101]=TS3TMA301 \
    [SV1VG0201]=SV1VMA101 \
    [SV1VG0101]=SV1VMA101 \
    [PA1AG0201]=PA1AMA101 \
    [PA1AG0101]=PA1AMA101 \
    [TR1AG0201]=TR1AMA101 \
    [TR1AG0101]=TR1AMA101 \
    [PR1PG0201]=PR1PMA101 \
    [PR1PG0101]=PR1PMA101 \
    )

# MQAWSADDR is an associative array using the AWS queue manager
# name as the index. The value of the element is the IP address
# of the AWS queue manager to which the gateway connects.
declare -A MQAWSADDR
MQAWSADDR=( \
    [CI1DMA101]=mq-ci1.icp.np.workcover.vic.gov.au \
    [DV1DMA201]=mq-dv1.icp.np.workcover.vic.gov.au \
    [PS1TMA101]=mq-ps1.icp.np.workcover.vic.gov.au \
    [TS1DMA301]=mq-ts1.icp.np.workcover.vic.gov.au \
    [TS2TMA201]=mq-ts2.icp.np.workcover.vic.gov.au \
    [TS3TMA301]=mq-ts3.icp.np.workcover.vic.gov.au \
    [TS4TMA201]=mq-ts4.icp.np.workcover.vic.gov.au \
    [SV1VMA101]=mq-sv1.icp.np.workcover.vic.gov.au \
    [PA1AMA101]=mq-pa1.icp.services.workcover.vic.gov.au \
    [TR1AMA101]=mq-tr1.icp.services.workcover.vic.gov.au \
    [PR1PMA101]=mq-pr1.icp.services.workcover.vic.gov.au \
    )

# MQAWSPORT is an associative array using the AWS queue manager
# name as the index. The value of the element is the TCP Port
# of the AWS queue manager to which the gateway connects.
declare -A MQAWSPORT
MQAWSPORT=( \
    [CI1DMA101]=31414 \
    [DV1DMA201]=31424 \
    [PS1TMA101]=31444 \
    [TS1DMA301]=31434 \
    [TS2TMA201]=31454 \
    [TS3TMA301]=31464 \
    [TS4TMA201]=31494 \
    [SV1VMA101]=31484 \
    [PA1AMA101]=32424 \
    [TR1AMA101]=32434 \
    [PR1PMA101]=32414 \
    )

# MQIIBLIST is an associative array using the actual queue manager
# name as the index. The value of the element is the name of the
# AWS queue manager to which the gateway connects.
declare -A MQIIBLIST
MQIIBLIST=( \
    [CI1DI0201]=CI1DMA101 \
    [CI1DI0101]=CI1DMA101 \
    [DV1DI0201]=DV1DMA201 \
    [DV1DI0101]=DV1DMA201 \
    [PS1DI0201]=PS1TMA101 \
    [PS1DI0101]=PS1TMA101 \
    [TS1TI0201]=TS4TMA201 \
    [TS1TI0101]=TS4TMA201 \
    [TS2TI0201]=TS3TMA301 \
    [TS2TI0101]=TS3TMA301 \
    [TS3TI0201]=TS3TMA301 \
    [TS3TI0101]=TS3TMA301 \
    [SV1VI0201]=SV1VMA101 \
    [SV1VI0101]=SV1VMA101 \
    [PA1AI0201]=PA1AMA101 \
    [PA1AI0101]=PA1AMA101 \
    [TR1AI0201]=TR1AMA101 \
    [TR1AI0101]=TR1AMA101 \
    [PR1PI0201]=PR1PMA101 \
    [PR1PI0101]=PR1PMA101 \
    )

# MuleSoft MQ

# MQMULELIST is an associative array using the actual queue manager
# name as the index. The value of the element is the name of the
# MuleSoft queue manager to which the gateway connects.
declare -A MQMULELIST
MQMULELIST=( \
    [DV1DG0201]=DV1DMA202 \
    [DV1DG0101]=DV1DMA202 \
    [TS1TG0201]=TS1TMA302 \
    [TS1TG0101]=TS1TMA302 \
    [TS1TG0201B]=TS4TMA302 \
    [TS1TG0101B]=TS4TMA302 \
    [TS2TG0201]=TS3TMA302 \
    [TS2TG0101]=TS3TMA302 \
    [SV1VG0201]=SV1VMA302 \
    [SV1VG0101]=SV1VMA302 \
    [PA1AG0201]=PA1AMA202 \
    [PA1AG0101]=PA1AMA202 \
    [TR1AG0201]=TR1AMA202 \
    [TR1AG0101]=TR1AMA202 \
    [PR1PG0201]=PR1PMA202 \
    [PR1PG0101]=PR1PMA202 \
    [PR1PG0201B]=PR1PMA302 \
    [PR1PG0101B]=PR1PMA302 \ 
    )

# MQMULEADDR is an associative array using the MuleSoft queue manager
# name as the index. The value of the element is the IP address
# of the MuleSoft queue manager to which the gateway connects.
declare -A MQMULEADDR
MQMULEADDR=( \
    [DV1DMA202]=wtuwmqa202.tstmelb.ad \
    [TS1TMA302]=wtuwmqa302.tstmelb.ad \
    [TS3TMA302]=wtuwmqa302.tstmelb.ad \
    [TS4TMA302]=wtuwmqa302.tstmelb.ad \
    [SV1VMA302]=wtuwmqa302.tstmelb.ad \
    [TR1AMA202]=wauwmqa202.melb.ad \
    [PA1AMA202]=wauwmqa202.melb.ad \
    [PR1PMA202]=wpuwmqa202.melb.ad \
    [PR1PMA302]=wpuwmqa302.melb.ad \
    )

# MQMULEPORT is an associative array using the MuleSoft queue manager
# name as the index. The value of the element is the TCP Port
# of the MuleSoft queue manager to which the gateway connects.
declare -A MQMULEPORT
MQMULEPORT=( \
    [DV1DMA202]=1414 \
    [TS1TMA302]=1415 \
    [TS3TMA302]=1416 \
    [TS4TMA302]=1417 \
    [SV1VMA302]=1418 \
    [TR1AMA202]=1416 \
    [PA1AMA202]=1415 \
    [PR1PMA202]=1414 \
    [PR1PMA302]=1414 \
    )
