#
# /opt/properties/mqldap.properties
#
# -   Map each cluster to the LDAP access information
#
# -   3 associative arrays are used to store the information.
#     The array index is the environment letter, formerly part of the host
#     name, in upper case.
#
# -   Derived from properties file in `itsshelper` repository
#
declare -A LDAPBindUsr
declare -A LDAPBindPW
declare -A LDAPConn
#
LDAPBindUsr[X]="cn=mq_bind_poc,ou=admin,o=vwa"
LDAPBindPW[X]="Ch87DZKBp9"
LDAPConn[X]="ldaps://wduent0201.services.workcover.vic.gov.au"
#
LDAPBindUsr[D]="cn=mq_bind_dev,ou=admin,o=vwa"
LDAPBindPW[D]="KIEcYEP2zvoJ9O5FuwiTwTLu"
LDAPConn[D]="ldaps://ldbenldap.services.workcover.vic.gov.au"
#
LDAPBindUsr[T]="cn=mq_bind_tst,ou=admin,o=vwa"
LDAPBindPW[T]="BUrLTmvyPxv6S8c1sxRyHH3b"
LDAPConn[T]="ldaps://ldbenldap.services.workcover.vic.gov.au"
#
LDAPBindUsr[V]="cn=mq_bind_tst,ou=admin,o=vwa"
LDAPBindPW[V]="BUrLTmvyPxv6S8c1sxRyHH3b"
LDAPConn[V]="ldaps://ldbenldap.services.workcover.vic.gov.au"
#
LDAPBindUsr[A]="cn=mq_bind_prd,ou=admin,o=vwa"
LDAPBindPW[A]="kFA2NgigTNGkzxvc9hhskRUd"
LDAPConn[A]="ldaps://ldbenldap.services.workcover.vic.gov.au"
#
LDAPBindUsr[P]="cn=mq_bind_prd,ou=admin,o=vwa"
LDAPBindPW[P]="kFA2NgigTNGkzxvc9hhskRUd"
LDAPConn[P]="ldaps://ldbenldap.services.workcover.vic.gov.au"
#
