#
# :Precis: Setup localhost for IBM ACE environments
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Setup host for IBM ACE
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    # Host-level ACE parameters
    ibm_ace_host_user: aceadmin
    ibm_ace_host_uid: 5001
    ibm_ace_host_group: mqbrkrs
    ibm_ace_host_gid: 5001
    ibm_ace_host_additional_groups:
      - mqm
    ibm_ace_host_users: []

  roles:
    - ibm_ace_host_config
