#
# :Precis: Define parameters for IBM MQ
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

galaxy_info:
  author: Andrew Burrow
  description: >-
    Define parameters for IBM MQ

    This *define role* describes the parameters controlling the installation
    and maintenance of IBM MQ for a host and environment on the host.

    See `../defaults/main.yml` for details on the parameters.
  company: Syntegrity Solutions

dependencies: []
