#
# :Precis: Setup SDUACE0101 for hosting IBM MQ environments
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Setup host for IBM MQ
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    # FROM ibm_mq_host_define
    #

    # Daemon user and groups
    #
    # What is the name and UID of the account to run the daemon?  What is
    # the name and GID of the primary group of the daemon?  Which
    # administrative users should be added to the primary group of the
    # daemon?
    ibm_mq_host_user: mqm
    ibm_mq_host_uid: 10779
    ibm_mq_host_group: mqm
    ibm_mq_host_gid: 10779
    ibm_mq_host_users: []

    # System resource limits for mqm user
    #
    # What are the soft and hard limits for open files (nofile) and processes
    # (nproc) for the mqm user?  These go in /etc/security/limits.conf.
    ibm_mq_host_nofile: 10240
    ibm_mq_host_nproc: 4096

    # Brokers group GID
    #
    # What is the GID for the mqbrkrs secondary group?  If not specified, the
    # system will auto-assign.
    # ibm_mq_host_brokers_gid: 5002

  roles:
    - ibm_mq_host_define
    - ibm_mq_host_config
