#
# :Precis: Define environment parameters for IBM MQ
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

# Environment identifier
#
# What is the short name for this environment?  This is used in directory
# paths and queue manager names.  Examples: sx1, ts1, ts2, prod
ibm_mq_environment: sx1

# MQ version and package
#
# What version of IBM MQ are we installing?  What is the filename of the
# installation package?  Where is it located?
ibm_mq_environment_version: "9.3.0.2"
ibm_mq_environment_package: "IBM_MQ_9.3.0.2_LINUX_X86-64.tar.gz"
ibm_mq_environment_source_dir: /var/tmp

# Build directory for RPM creation
#
# Where should we create the ephemeral workspace for building custom RPMs?
# This directory can be deleted after installation.
ibm_mq_environment_build_dir: "/var/tmp/{{ ibm_mq_environment }}/mq-build"

# MQ fixpack version and package
#
# What fixpack level should be applied?  What is the filename of the
# fixpack package?
ibm_mq_environment_fixpack_version: "9.3.0.16"
ibm_mq_environment_fixpack_package: "9.3.0-IBM-MQ-LinuxX64-FP0016.tar.gz"

# Queue manager creation
#
# Which itsshelper prop files should be run to create queue managers in
# this environment?  The specifications comprise a list of objects that
# define the following keys:
#
# - `queue_manager` -- What is the host-specific name of the queue manager?
#   It must match the queue manager name computed in the `itsshelper` prop
#   file
# - `desc` -- What is a human-readable description of the queue manager
#   created by this prop file?
# - `propfile` -- What is the basename of the prop file, less the `.prop`
#   extension?  This is passed as the second argument to `translate.bash`.
# - `qmtype` -- What is the queue manager typed?  For example, `Apps` or
#   `Jumbo`.  It must match the type recorded in the `itsshelper` prop file
#
# HOST OVERRIDE CONVENTIONS:
#
# - The `queue_manager` value is environment-specific AND host-specific
# - The host specific value is computed at task execution time from an
#   expression that uses `ibm_host_index`
# - The variable SHOULD NOT and NEED NOT be overridden in the host variables
#   IF expressed in terms of `ibm_host_index`
ibm_mq_environment_itsshelper_qmgr_props: []

# MQ application queue configuration
#
# Which itsshelper prop files should be run against the queue managers
# in this environment?  The specifications comprise a list of objects
# that define the following keys:
#
# - `queue_manager` -- What is the host-specific name of the queue manager to
#   which the application is being configured?  It must match the queue
#   manager name computed in the `itsshelper` prop file
# - `desc` -- What is a human-readable description of the queues
#   configured by this prop file?
# - `propfile` -- What is the basename of the prop file, less the `.prop`
#   extension?  This is passed as the second argument to `translate.bash`.
# - `qmtype` -- What is the queue manager type.  It must match the type
#   recorded in the `itsshelper` prop file
#
# HOST OVERRIDE CONVENTIONS:
#
# - The `queue_manager` value is environment-specific AND host-specific
# - The host specific value is computed at task execution time from an
#   expression that uses `ibm_host_index`
# - The variable SHOULD NOT and NEED NOT be overridden in the host variables
#   IF expressed in terms of `ibm_host_index`
ibm_mq_environment_itsshelper_mqapp_props: []
