#
# :Precis: Config the host for IBM MQ installs
# :Authors: Andrew Burrow
# :Contact: andrew.burrow@syntegrity.com.au
#

---

- name: Create mqm group
  become: true
  ansible.builtin.group:
    name: "{{ ibm_mq_host_group }}"
    gid: "{{ ibm_mq_host_gid | default(omit) }}"
    state: present

- name: Add root to mqm group
  become: true
  ansible.builtin.user:
    name: root
    groups: "{{ ibm_mq_host_group }}"
    append: true

- name: Create mqbrkrs group
  become: true
  ansible.builtin.group:
    name: "{{ ibm_mq_host_brokers_group }}"
    gid: "{{ ibm_mq_host_brokers_gid | default(omit) }}"
    state: present

- name: Create mqm user
  become: true
  ansible.builtin.user:
    name: "{{ ibm_mq_host_user }}"
    uid: "{{ ibm_mq_host_uid | default(omit) }}"
    group: "{{ ibm_mq_host_group }}"
    password: "!"
    password_lock: true
    password_expire_min: 0
    password_expire_max: 99999
    state: present

- name: Create MQ data directory
  become: true
  ansible.builtin.file:
    path: /var/mqm
    state: directory
    mode: '0775'
    group: "{{ ibm_mq_host_group }}"

- name: Add administrative users to mqm group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ ibm_mq_host_group }}"
    append: true
  loop: "{{ ibm_mq_host_users }}"
  when: ibm_mq_host_users | length > 0

- name: Configure system limits for mqm user
  become: true
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      {{ ibm_mq_host_user }}    soft    nofile    {{ ibm_mq_host_nofile }}
      {{ ibm_mq_host_user }}    hard    nofile    {{ ibm_mq_host_nofile }}
      {{ ibm_mq_host_user }}    soft    nproc     {{ ibm_mq_host_nproc }}
      {{ ibm_mq_host_user }}    hard    nproc     {{ ibm_mq_host_nproc }}
    marker: "# {mark} ANSIBLE MANAGED MQM LIMITS"

- name: Install bc package for MQ
  become: true
  ansible.builtin.dnf:
    name: bc
    state: present

- name: Create itsshelper properties directory
  become: true
  ansible.builtin.file:
    path: /opt/properties
    state: directory
    mode: '0775'
    group: "{{ ibm_mq_host_group }}"

- name: Create itsshelper scripts directory
  become: true
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    owner: root
    group: "{{ ibm_mq_host_group }}"
    mode: '0775'

- name: Copy itsshelper MQ property files
  become: true
  ansible.builtin.copy:
    src: itsshelper/files/eip_properties/iibwmq/
    dest: /opt/properties/
    owner: root
    group: "{{ ibm_mq_host_group }}"
    mode: "0644"

- name: Copy itsshelper MQ scripts
  become: true
  ansible.builtin.copy:
    src: itsshelper/files/eip_scripts/iibwmq/
    dest: /opt/scripts/
    owner: root
    group: "{{ ibm_mq_host_group }}"
    mode: "0755"

- name: Copy in password salt from vault
  become: true
  ansible.builtin.copy:
    content: "{{ ibm_mq_host_pwd_salt }}"
    dest: /opt/properties/pwd_salt
    owner: root
    group: root
    mode: "0400"
